In [2]:
# Import machine learning dependencies
import sqlite3
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [3]:
con = sqlite3.connect("mushrooms.db")
cur = con.cursor()

In [ ]:
#df = pd.read_csv('mushrooms.csv')

In [ ]:
#df_features = df.drop(['class'], axis=1)
#df_target = df[['class']]

In [ ]:
#sql_cols = 'create table mushroom_features (id number, '
#for col in df_features.columns:
#    sql_cols += col + ' varchar,\n'
    
#create_features = f"{sql_cols[:-2]})"

In [ ]:
 #print(create_features)

In [ ]:
#cur.execute(create_features)

In [ ]:
# all_data = []
# for i, row in df_features.iterrows():
#     one_row = [i]
#     for col in row:
#         one_row.append(col)
#     all_data.append(one_row)

In [ ]:
# cur.executemany('insert into mushroom_features values (:1, :2, :3, :4, :5, :6, :7, :8, :9, :10, :11, :12, :13, :14, :15, :16, :17, :18, :19, :20, :21, :22, :23)', all_data)
# con.commit()

In [ ]:
# select_all = "SELECT * FROM mushroom_features"
# rows = cur.execute(select_all).fetchall()

In [ ]:
# for r in rows:
#     print(r)

In [ ]:
# create_target = "create table mushroom_targets (id number, class)"

In [ ]:
# cur.execute(create_target)

In [ ]:
# all_data_targets = []
# for i, row in df_target.iterrows():
#   one_row = [i]
#   for col in row:
#     one_row.append(col)
#   all_data_targets.append(one_row)

# all_data_targets

In [ ]:
# cur.executemany('insert into mushroom_targets values (:1, :2)', all_data_targets)
# con.commit()

In [ ]:
# pd.read_sql('select * from mushroom_targets', con)

In [ ]:
# select_targets = "SELECT * FROM mushroom_targets"
# target_rows = cur.execute(select_targets).fetchall()

In [ ]:
# for tr in target_rows:
#   print(tr)

In [ ]:
# SELECT * FROM mushroom_targets JOIN mushroom_features ON mushroom_targets.id = mushroom_features.id

In [ ]:
# join_tables = "SELECT * FROM mushroom_targets JOIN mushroom_features ON mushroom_targets.id = mushroom_features.id"

In [ ]:
# join = cur.execute(join_tables).fetchall()

In [ ]:
# for row in join:
#     print(row)

In [ ]:
# mushroom_df = pd.read_sql('SELECT * FROM mushroom_targets JOIN mushroom_features ON mushroom_targets.id = mushroom_features.id', con)

# mushroom_df

In [ ]:
# Add code here to clean and prepare the data

# le = LabelEncoder()

# mushroom_df= mushroom_df.apply(LabelEncoder().fit_transform)

In [ ]:
# mushroom_df

In [5]:
df_f = pd.read_sql('select * from mushroom_features', con)
df_f

,id,cap_shape,cap_surface,cap_color,bruises,odor,gill_attachment,gill_spacing,gill_size,gill_color,...,stalk_surface_below_ring,stalk_color_above_ring,stalk_color_below_ring,veil_type,veil_color,ring_number,ring_type,spore_print_color,population,habitat
0,0,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,1,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,2,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,3,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,4,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,8119,k,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,b,c,l
8120,8120,x,s,n,f,n,a,c,b,y,...,s,o,o,p,n,o,p,b,v,l
8121,8121,f,s,n,f,n,a,c,b,n,...,s,o,o,p,o,o,p,b,c,l
8122,8122,k,y,n,f,y,f,c,n,b,...,k,w,w,p,w,o,e,w,v,l
8123,8123,x,s,n,f,n,a,c,b,y,...,s,o,o,p,o,o,p,o,c,l

In [6]:
df_t = pd.read_sql('select * from mushroom_targets', con)
df_t

        id class
0        0     p
1        1     e
2        2     e
3        3     p
4        4     e
...    ...   ...
8119  8119     e
8120  8120     e
8121  8121     e
8122  8122     p
8123  8123     e

[8124 rows x 2 columns]

In [17]:
# Define the features and target

X = df_f.drop(["id"], axis=1)

y = df_t['class']

In [18]:
for col in X.columns:
    X[col] = LabelEncoder().fit_transform(X[col])

In [19]:
X

,cap_shape,cap_surface,cap_color,bruises,odor,gill_attachment,gill_spacing,gill_size,gill_color,stalk_shape,...,stalk_surface_below_ring,stalk_color_above_ring,stalk_color_below_ring,veil_type,veil_color,ring_number,ring_type,spore_print_color,population,habitat
0,5,2,4,1,6,1,0,1,4,0,...,2,7,7,0,2,1,4,2,3,5
1,5,2,9,1,0,1,0,0,4,0,...,2,7,7,0,2,1,4,3,2,1
2,0,2,8,1,3,1,0,0,5,0,...,2,7,7,0,2,1,4,3,2,3
3,5,3,8,1,6,1,0,1,5,0,...,2,7,7,0,2,1,4,2,3,5
4,5,2,3,0,5,1,1,0,4,1,...,2,7,7,0,2,1,0,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,3,2,4,0,5,0,0,0,11,0,...,2,5,5,0,1,1,4,0,1,2
8120,5,2,4,0,5,0,0,0,11,0,...,2,5,5,0,0,1,4,0,4,2
8121,2,2,4,0,5,0,0,0,5,0,...,2,5,5,0,1,1,4,0,1,2
8122,3,3,4,0,8,1,0,1,0,1,...,1,7,7,0,2,1,0,7,4,2
8123,5,2,4,0,5,0,0,0,11,0,...,2,5,5,0,1,1,4,4,1,2

In [20]:
# Split into training and testing sets
## Stratify?
## Check what random state should be set to

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [ ]:
# Create a standard scaler instance
# scaler = StandardScaler()

# # Fit the Standard Scaler with the training data
# X_scaler = scaler.fit(X_train)

# # Scale the data
# X_train_scaled = X_scaler.transform(X_train)
# X_test_scaled = X_scaler.transform(X_test)

In [21]:
# Create a random forest classifier.
## Check what number of estimators should be and what random state should be set to

rf_model = RandomForestClassifier(n_estimators=128, random_state=78)

In [23]:
# Fit the model

rf_model = rf_model.fit(X_train, y_train)

In [24]:
# Make predictions using the testing data

predictions = rf_model.predict(X_test)

In [25]:
# Create the confusion matrix and a dataframe

cm = confusion_matrix(y_test, predictions)

cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"])

In [26]:
cm_df

          Predicted 0  Predicted 1
Actual 0         1048            0
Actual 1            0          983

In [27]:
# Calculate the accuracy score

acc_score = accuracy_score(y_test, predictions)

In [28]:
# Display results

print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0         1048            0
Actual 1            0          983

Accuracy Score : 1.0
Classification Report
              precision    recall  f1-score   support

           e       1.00      1.00      1.00      1048
           p       1.00      1.00      1.00       983

    accuracy                           1.00      2031
   macro avg       1.00      1.00      1.00      2031
weighted avg       1.00      1.00      1.00      2031

In [29]:
# Calculate feature importance in the Random Forest model.
#The output from this code returns an array of scores for the features in the X_test set, whose sum equals 1.0:
importances = rf_model.feature_importances_
importances

array([0.00472861, 0.00853296, 0.01168102, 0.04957004, 0.15228304,
       0.00350804, 0.05244693, 0.10548454, 0.10171477, 0.02864228,
       0.05442542, 0.04628943, 0.05123152, 0.02397798, 0.01695259,
       0.        , 0.00201934, 0.01322657, 0.08221886, 0.10070301,
       0.05259085, 0.0377722 ])

In [30]:
# Sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.1522830399381663, 'odor'),
 (0.10548454435023337, 'gill_size'),
 (0.10171477478872035, 'gill_color'),
 (0.10070300678133833, 'spore_print_color'),
 (0.08221885567582286, 'ring_type'),
 (0.05442542008834844, 'stalk_root'),
 (0.0525908515982156, 'population'),
 (0.052446926438851876, 'gill_spacing'),
 (0.051231521493581726, 'stalk_surface_below_ring'),
 (0.04957003762064024, 'bruises'),
 (0.04628942828831537, 'stalk_surface_above_ring'),
 (0.037772199032309585, 'habitat'),
 (0.02864227869894102, 'stalk_shape'),
 (0.023977982526642364, 'stalk_color_above_ring'),
 (0.016952588970309504, 'stalk_color_below_ring'),
 (0.013226570924077627, 'ring_number'),
 (0.011681018243977173, 'cap_color'),
 (0.008532961786219333, 'cap_surface'),
 (0.004728613964602275, 'cap_shape'),
 (0.0035080424657842582, 'gill_attachment'),
 (0.0020193363249024986, 'veil_color'),
 (0.0, 'veil_type')]